<a href="https://colab.research.google.com/github/WarriorX21/FDS_Assignment2/blob/main/FDS_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import linalg

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

# Matrix Addition
add_result = A + B
print("\nAddition (A + B):")
print(add_result)

# Matrix Subtraction
sub_result = A - B
print("\nSubtraction (A - B):")
print(sub_result)

# Matrix Multiplication
mult_result = np.matmul(A, B)  # or simply A @ B
print("\nMultiplication (A * B):")
print(mult_result)

# Element-wise Multiplication
elem_mult = A * B
print("\nElement-wise Multiplication (A .* B):")
print(elem_mult)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:")
print(det_A)

# Matrix Inverse
try:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:")
    print(inv_A)

    # Verify the inverse: A * A^-1 should be the identity matrix
    print("\nVerify inverse (A * A^-1):")
    print(np.matmul(A, inv_A))
except np.linalg.LinAlgError:
    print("Matrix is not invertible")

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
print("\nEigenvectors of A (as columns):")
print(eigenvectors)

# Check Orthogonality of Eigenvectors
# Normalize the eigenvectors
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

print("\nNormalized Eigenvectors:")
print(normalized_eigenvectors)

# Calculate dot products between eigenvectors
# If orthogonal, dot product should be close to 0
dot_product = np.dot(normalized_eigenvectors[:, 0], normalized_eigenvectors[:, 1])
print("\nDot product of eigenvectors:")
print(dot_product)

if abs(dot_product) < 1e-10:
    print("Eigenvectors are orthogonal")
else:
    print("Eigenvectors are not orthogonal")

# Calculate Span and Basis of Vector Space
# Let's create a set of vectors
vectors = np.array([[1, 2, 3], [2, 4, 6], [0, 1, 2], [1, 0, 1]])
print("\nSet of vectors:")
print(vectors)

# Calculate rank to find the dimension of the span
rank = np.linalg.matrix_rank(vectors)
print("\nRank (dimension of span):", rank)

# Find a basis using row echelon form (via QR decomposition)
Q, R = np.linalg.qr(vectors.T)
basis = Q[:, :rank]
print("\nOrthonormal basis for the span:")
print(basis)

# Alternative: Find basis using SVD
U, S, Vh = np.linalg.svd(vectors, full_matrices=False)
# Keep only the vectors corresponding to non-zero singular values
significant_singular_values = S > 1e-10
svd_basis = U[:, significant_singular_values]
print("\nBasis found using SVD:")
print(svd_basis)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]

Addition (A + B):
[[ 6  8]
 [10 12]]

Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

Multiplication (A * B):
[[19 22]
 [43 50]]

Element-wise Multiplication (A .* B):
[[ 5 12]
 [21 32]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verify inverse (A * A^-1):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Eigenvalues of A:
[-0.37228132  5.37228132]

Eigenvectors of A (as columns):
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Normalized Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Dot product of eigenvectors:
-0.17149858514250893
Eigenvectors are not orthogonal

Set of vectors:
[[1 2 3]
 [2 4 6]
 [0 1 2]
 [1 0 1]]

Rank (dimension of span): 3

Orthonormal basis for the span:
[[-0.26726124  0.95618289  0.11952286]
 [-0.53452248 -0.04390192 -0.84401323]
 [-0.80178373 -0.28945968  0.52283453]]

Basis found using SVD:
[[-4.29883508e-01 -2.77555756e-16  1.23288